<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete selected items?' => '',
    'Are you sure you want to delete this item?' => '',
    'Article Categories' => '',
    'Articles' => '',
    'Articles' => '',
    'Cancel' => '',
    'Carousel Widgets' => '',
    'Content' => '',
    'Create' => '',
    'Dashboard' => '',
    'Delete' => '',
    'Delete selected' => '',
    'File Manager' => '',
    'File Storage Items' => '',
    'Hello, {name}' => '',
    'Home' => '',
    'Key-Value Storage' => '',
    'Logs' => '',
    'Member since' => '',
    'Menu Widgets' => '',
    'Profile' => '',
    'Sign out' => '',
    'Static pages' => '',
    'System' => '',
    'System Events' => '',
    'System Information' => '',
    'Text Widgets' => '',
    'Toggle navigation' => '',
    'Users' => '',
    'View all' => '',
    'You have {num} events' => '',
    'You have {num} log items' => '',
    'You need to select at least one item.' => '',
];
