<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ATTR_CREATED' => 'Created at',
    'ATTR_EMAIL' => 'E-mail',
    'ATTR_PASSWORD' => 'Password',
    'ATTR_REPASSWORD' => 'Repeat password',
    'ATTR_ROLE' => 'Role',
    'ATTR_STATUS' => 'Status',
    'ATTR_UPDATED' => 'Updated at',
    'ATTR_USERNAME' => 'Username',
    'BACKEND_CREATE_SUBMIT' => 'Save',
    'BACKEND_CREATE_SUBTITLE' => 'User creating',
    'BACKEND_CREATE_TITLE' => 'Users',
    'BACKEND_FLASH_FAIL_ADMIN_CREATE' => 'User has not been saved. Please try again!',
    'BACKEND_INDEX_SUBTITLE' => 'Users list',
    'BACKEND_INDEX_TITLE' => 'Users',
    'BACKEND_LOGIN_RECOVERY' => 'Recover password',
    'BACKEND_LOGIN_SUBMIT' => 'Sign In',
    'BACKEND_LOGIN_TITLE' => 'Sign In',
    'BACKEND_PROMPT_ROLE' => 'Select role',
    'BACKEND_PROMPT_STATUS' => 'Select status',
    'BACKEND_UPDATE_SUBMIT' => 'Update',
    'BACKEND_UPDATE_SUBTITLE' => 'User updating',
    'BACKEND_UPDATE_TITLE' => 'Users',
    'FRONTEND_EMAIL_CHANGE_SUBMIT' => 'Change',
    'FRONTEND_EMAIL_CHANGE_TITLE' => 'Change e-mail address',
    'FRONTEND_PASSWORD_CHANGE_SUBMIT' => 'Change',
    'FRONTEND_PASSWORD_CHANGE_TITLE' => 'Change password',
    'FRONTEND_RECOVERY_CONFIRMATION_SUBMIT' => 'Save',
    'FRONTEND_RECOVERY_CONFIRMATION_TITLE' => 'Password recovery',
    'FRONTEND_RECOVERY_SUBMIT' => 'Recover',
    'FRONTEND_RECOVERY_TITLE' => 'Password recovery',
    'FRONTEND_RESEND_SUBMIT' => 'Resend',
    'FRONTEND_RESEND_TITLE' => 'Resend e-mail confirmation',
    'FRONTEND_SIGNUP_RESEND' => 'Resend e-mail confirmation',
    'FRONTEND_SIGNUP_SUBMIT' => 'Sign Up',
    'FRONTEND_SIGNUP_TITLE' => 'Sign Up',
    'FRONTEND_UPDATE_SUBMIT' => 'Update',
    'FRONTEND_UPDATE_TITLE' => 'Update user profile',
    'STATUS_ACTIVE' => 'Active',
    'STATUS_BANNED' => 'Banned',
    'STATUS_INACTIVE' => 'Inactive',
];
