<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete selected items?' => 'Вы уверены, что хотите удалить выбранные элементы?',
    'Are you sure you want to delete this item?' => 'Вы уверены, что хотите удалить этот пункт?',
    'Are you sure you want to delete all' => 'Вы уверены, что хотите удалить всё?',
    'Article Categories' => 'Категории стататей',
    'Articles' => 'Статьи',
    'Articles category' => 'Категории статей',
    'Cancel' => 'Отмена',
    'Carousel Widgets' => 'Виджет карусель',
    'Content' => 'Контент',
    'Create' => 'Создание',
    'Dashboard' => 'Панель управления',
    'Delete' => 'Удалить',
    'Delete all' => 'Удалить всё',
    'Delete selected' => 'Удалить выбранные',
    'File Manager' => 'Менеджер файлов',
    'File Storage Items' => '',
    'Hello, {name}' => 'Привет, {name}',
    'Home' => 'Главная',
    'Key-Value Storage' => 'Ключ-значение ',
    'Logs' => 'Журнал',
    'Member since' => 'На сайте с',
    'Menu Widgets' => 'Меню Виджет',
    'Profile' => 'Профиль',
    'Sign out' => 'Выйти из системы',
    'Static pages' => 'Статические страницы',
    'System' => 'Система',
    'System Events' => 'Системные события',
    'System Information' => 'Системная информация',
    'Text Widgets' => 'Текстовый Виджет',
    'Toggle navigation' => '',
    'Users' => 'Пользователи',
    'View all' => 'Переключить навигации',
    'You have {num} events' => '',
    'You have {num} log items' => '',
    'You need to select at least one item.' => 'Вы должны выбрать хотя бы один элемент.',
];
