<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ATTR_CREATED' => 'Дата добавления',
    'ATTR_EMAIL' => 'E-mail',
    'ATTR_PASSWORD' => 'Пароль',
    'ATTR_REPASSWORD' => 'Повторите пароль',
    'ATTR_ROLE' => 'Роль',
    'ATTR_STATUS' => 'Статус',
    'ATTR_UPDATED' => 'Дата обновления',
    'ATTR_USERNAME' => 'Логин',
    'BACKEND_CREATE_SUBMIT' => 'Сохранить',
    'BACKEND_CREATE_SUBTITLE' => 'Создание пользователя',
    'BACKEND_CREATE_TITLE' => 'Пользователи',
    'BACKEND_FLASH_FAIL_ADMIN_CREATE' => 'В момент создания нового пользователя возникла ошибка.',
    'BACKEND_INDEX_SUBTITLE' => 'Список пользователей',
    'BACKEND_INDEX_TITLE' => 'Пользователи',
    'BACKEND_LOGIN_RECOVERY' => 'Восстановить пароль',
    'BACKEND_LOGIN_SUBMIT' => 'Войти',
    'BACKEND_LOGIN_TITLE' => 'Авторизация',
    'BACKEND_PROMPT_ROLE' => 'Выберите роль',
    'BACKEND_PROMPT_STATUS' => 'Выберите статус',
    'BACKEND_UPDATE_SUBMIT' => 'Обновить',
    'BACKEND_UPDATE_SUBTITLE' => 'Обновление пользователя',
    'BACKEND_UPDATE_TITLE' => 'Пользователи',
    'FRONTEND_EMAIL_CHANGE_SUBMIT' => 'Изменить',
    'FRONTEND_EMAIL_CHANGE_TITLE' => 'Изменение адреса электронной почты',
    'FRONTEND_PASSWORD_CHANGE_SUBMIT' => 'Изменить',
    'FRONTEND_PASSWORD_CHANGE_TITLE' => 'Смена пароля',
    'FRONTEND_RECOVERY_CONFIRMATION_SUBMIT' => 'Сохранить',
    'FRONTEND_RECOVERY_CONFIRMATION_TITLE' => 'Восстановление пароля',
    'FRONTEND_RECOVERY_SUBMIT' => 'Восстановить',
    'FRONTEND_RECOVERY_TITLE' => 'Восстановления пароля',
    'FRONTEND_RESEND_SUBMIT' => 'Отправить',
    'FRONTEND_RESEND_TITLE' => 'Повторная отправка e-mail подтверждения',
    'FRONTEND_SIGNUP_RESEND' => 'Повторная отправка e-mail подтверждения',
    'FRONTEND_SIGNUP_SUBMIT' => 'Зарегистрироватся',
    'FRONTEND_SIGNUP_TITLE' => 'Регистрация',
    'FRONTEND_UPDATE_SUBMIT' => 'Обновить',
    'FRONTEND_UPDATE_TITLE' => 'Редактирование профиля',
    'STATUS_ACTIVE' => 'Активный',
    'STATUS_BANNED' => 'Забаненый',
    'STATUS_INACTIVE' => 'Неактивный',
];
