<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'CPU Usage' => 'Использование ЦП',
    'Category' => 'Категория',
    'Clear' => 'Очистить',
    'DB Type' => 'Тип БД',
    'DB Version' => 'Версия БД',
    'External IP' => 'Внешний IP',
    'Files in storage' => 'Файлы в хранилище',
    'Free Swap' => 'Свободная Swap',
    'Free memory' => 'Свободная память',
    'Hostname' => 'Имя хоста',
    'ID' => '',
    'Internal IP' => 'Внутренний IP',
    'Kernel version' => 'Версия ядра',
    'Level' => 'Уровень',
    'Load average' => 'Средняя нагрузка',
    'Log Time' => 'Log Time',
    'Memory' => 'Память',
    'Memory Usage' => 'Использование памяти',
    'Message' => 'Сообщение',
    'More info' => 'Подробнее',
    'Network' => 'Сеть',
    'New user' => 'Новый пользователь',
    'Новый пользователь {username} ({email}) был зарегистрирован {created_at, date} {created_at, time}' => '',
    'Number of cores' => 'Количество ядер',
    'OS' => 'ОС',
    'OS Release' => 'ОС Выпуска',
    'Off' => 'Выключить',
    'On' => 'Включить',
    'Operating System' => 'Операционная система',
    'PHP Version' => 'PHP версия',
    'Port' => 'Порт',
    'Prefix' => 'Преффикс',
    'Processor' => 'Процессор',
    'Processor Architecture' => 'Архетиктура процессора',
    'Real time' => 'Время',
    'Reset' => 'Рестарт',
    'Search' => 'Поиск',
    'Software' => 'Программное обеспечение',
    'System Events' => 'Системные события',
    'System Information' => 'Системная информация',
    'System Logs' => 'Системный журнал',
    'Total Swap' => 'Всего Swap',
    'Total memory' => 'Всего памяти',
    'Uptime' => 'Проведено на сайте',
    'User Registrations' => 'Регистраций пользователей',
    'Web Server' => 'Веб-сервер',
    '{uptime, duration}' => '',
];
