<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Alias' => '',
    'Are you sure you want to delete this item?' => '',
    'BACKEND_CANCEL_BTN_TITLE' => '',
    'BACKEND_CREATE_SUBTITLE' => '',
    'BACKEND_CREATE_TITLE' => '',
    'BACKEND_INDEX_SUBTITLE' => '',
    'BACKEND_INDEX_TITLE' => '',
    'Categories' => '',
    'Close' => '',
    'Create' => '',
    'Delete' => '',
    'ID' => '',
    'Level' => '',
    'Lft' => '',
    'Meta Description' => '',
    'Meta Keywords' => '',
    'Meta Title' => '',
    'Reset' => '',
    'Rgt' => '',
    'Root' => '',
    'STATUS_PUBLISHED' => '',
    'STATUS_UNPUBLISHED' => '',
    'Search' => '',
    'Status' => '',
    'Title' => '',
    'Update' => '',
    'Update {modelClass}: ' => '',
];
