<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ATTR_CREATED' => 'Дата добавления',
    'ATTR_EMAIL' => 'E-mail',
    'ATTR_NAME' => 'Имя',
    'ATTR_PASSWORD' => 'Пароль',
    'ATTR_REMEMBER_ME' => 'Запонить меня',
    'ATTR_ROLE' => 'Роль',
    'ATTR_STATUS' => 'Статус',
    'ATTR_SURNAME' => 'Фамилия',
    'ATTR_UPDATED' => 'Дата обновления',
    'ATTR_USERNAME' => 'Логин',
    'ERROR_MSG_INVALID_USERNAME_OR_PASSWORD' => 'Неправильный логин или пароль',
];
